# Generated by Django 3.2.2 on 2021-06-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todomodel_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='modified',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
