# Generated by Django 3.2.2 on 2021-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='modified',
            field=models.TimeField(auto_now=True),
        ),
    ]
